name: Build and push packages
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }}
        -n ggroupp -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # CustomerSet.Search.InOut.csproj

    - name: Restore CustomerSet.Search.InOut.csproj
      run: dotnet restore ./src/*/*/CustomerSet.Search.InOut.csproj

    - name: Build CustomerSet.Search.InOut.csproj
      run: dotnet build ./src/*/*/CustomerSet.Search.InOut.csproj --no-restore  -c Release

    - name: Pack CustomerSet.Search.InOut.csproj
      run: dotnet pack ./src/*/*/CustomerSet.Search.InOut.csproj --no-build -o ~/nuget  -c Release

    # CustomerSet.Search.Api.csproj

    - name: Restore CustomerSet.Search.Api.csproj
      run: dotnet restore ./src/*/*/CustomerSet.Search.Api.csproj

    - name: Build CustomerSet.Search.Api.csproj
      run: dotnet build ./src/*/*/CustomerSet.Search.Api.csproj --no-restore  -c Release

    - name: Pack CustomerSet.Search.Api.csproj
      run: dotnet pack ./src/*/*/CustomerSet.Search.Api.csproj --no-build -o ~/nuget  -c Release

    # CustomerSet.Search.Api.Tests.csproj

    - name: Restore CustomerSet.Search.Api.Tests.csproj
      run: dotnet restore ./src/*/*/CustomerSet.Search.Api.Tests.csproj

    - name: Test CustomerSet.Search.Api.Tests.csproj
      run: dotnet test ./src/*/*/CustomerSet.Search.Api.Tests.csproj --no-restore  -c Release

    # ContactSet.Search.InOut.csproj

    - name: Restore ContactSet.Search.InOut.csproj
      run: dotnet restore ./src/*/*/ContactSet.Search.InOut.csproj

    - name: Build ContactSet.Search.InOut.csproj
      run: dotnet build ./src/*/*/ContactSet.Search.InOut.csproj --no-restore  -c Release

    - name: Pack ContactSet.Search.InOut.csproj
      run: dotnet pack ./src/*/*/ContactSet.Search.InOut.csproj --no-build -o ~/nuget  -c Release

     # ContactSet.Search.Api.csproj

    - name: Restore ContactSet.Search.Api.csproj
      run: dotnet restore ./src/*/*/ContactSet.Search.Api.csproj

    - name: Build ContactSet.Search.Api.csproj
      run: dotnet build ./src/*/*/ContactSet.Search.Api.csproj --no-restore  -c Release

    - name: Pack ContactSet.Search.Api.csproj
      run: dotnet pack ./src/*/*/ContactSet.Search.Api.csproj --no-build -o ~/nuget  -c Release

    # ContactSet.Search.Api.Tests.csproj

    - name: Restore ContactSet.Search.Api.Tests.csproj
      run: dotnet restore ./src/*/*/ContactSet.Search.Api.Tests.csproj

    - name: Test ContactSet.Search.Api.Tests.csproj
      run: dotnet test ./src/*/*/ContactSet.Search.Api.Tests.csproj --no-restore  -c Release

    # UserSet.Search.InOut.csproj

    - name: Restore UserSet.Search.InOut.csproj
      run: dotnet restore ./src/*/*/UserSet.Search.InOut.csproj

    - name: Build UserSet.Search.InOut.csproj
      run: dotnet build ./src/*/*/UserSet.Search.InOut.csproj --no-restore  -c Release

    - name: Pack UserSet.Search.InOut.csproj
      run: dotnet pack ./src/*/*/UserSet.Search.InOut.csproj --no-build -o ~/nuget  -c Release

     # UserSet.Search.Api.csproj

    - name: Restore UserSet.Search.Api.csproj
      run: dotnet restore ./src/*/*/UserSet.Search.Api.csproj

    - name: Build UserSet.Search.Api.csproj
      run: dotnet build ./src/*/*/UserSet.Search.Api.csproj --no-restore  -c Release

    - name: Pack UserSet.Search.Api.csproj
      run: dotnet pack ./src/*/*/UserSet.Search.Api.csproj --no-build -o ~/nuget  -c Release

    # UserSet.Search.Api.Tests.csproj

    - name: Restore UserSet.Search.Api.Tests.csproj
      run: dotnet restore ./src/*/*/UserSet.Search.Api.Tests.csproj

    - name: Test UserSet.Search.Api.Tests.csproj
      run: dotnet test ./src/*/*/UserSet.Search.Api.Tests.csproj --no-restore  -c Release

    # Incident.Create.InOut.csproj

    - name: Restore Incident.Create.InOut.csproj
      run: dotnet restore ./src/*/*/Incident.Create.InOut.csproj

    - name: Build Incident.Create.InOut.csproj
      run: dotnet build ./src/*/*/Incident.Create.InOut.csproj --no-restore  -c Release

    - name: Pack Incident.Create.InOut.csproj
      run: dotnet pack ./src/*/*/Incident.Create.InOut.csproj --no-build -o ~/nuget  -c Release

    # Incident.Create.Api.csproj

    - name: Restore Incident.Create.Api.csproj
      run: dotnet restore ./src/*/*/Incident.Create.Api.csproj

    - name: Build Incident.Create.Api.csproj
      run: dotnet build ./src/*/*/Incident.Create.Api.csproj --no-restore  -c Release

    - name: Pack Incident.Create.Api.csproj
      run: dotnet pack ./src/*/*/Incident.Create.Api.csproj --no-build -o ~/nuget  -c Release

    # Incident.Create.Api.Tests.csproj

    - name: Restore Incident.Create.Api.Tests.csproj
      run: dotnet restore ./src/*/*/Incident.Create.Api.Tests.csproj

    - name: Test Incident.Create.Api.Tests.csproj
      run: dotnet test ./src/*/*/Incident.Create.Api.Tests.csproj --no-restore  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ secrets.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate
