name: Build and push packages
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

     # Add NuGet Sources

    - name: Create Local NuGet Directory
      run: mkdir ~/nuget

    - name: Add Local Nuget Source
      run: dotnet nuget add source ~/nuget

    - name: Add GGroupp NuGet Source
      run: >
        dotnet nuget add source ${{ secrets.GG_NUGET_SOURCE_URL }}
        -n ggroupp -u ${{ secrets.GG_NUGET_SOURCE_USER_NAME }}
        -p ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --store-password-in-clear-text

    # Api.Contract.ContactSet.Search.csproj

    - name: Restore Api.Contract.ContactSet.Search.csproj
      run: dotnet restore ./src/*/*/Api.Contract.ContactSet.Search.csproj

    - name: Build Api.Contract.ContactSet.Search.csproj
      run: dotnet build ./src/*/*/Api.Contract.ContactSet.Search.csproj --no-restore  -c Release

    - name: Pack Api.Contract.ContactSet.Search.csproj
      run: dotnet pack ./src/*/*/Api.Contract.ContactSet.Search.csproj --no-build -o ~/nuget  -c Release

    # Api.Contract.CustomerSet.Search.csproj

    - name: Restore Api.Contract.CustomerSet.Search.csproj
      run: dotnet restore ./src/*/*/Api.Contract.CustomerSet.Search.csproj

    - name: Build Api.Contract.CustomerSet.Search.csproj
      run: dotnet build ./src/*/*/Api.Contract.CustomerSet.Search.csproj --no-restore  -c Release

    - name: Pack Api.Contract.CustomerSet.Search.csproj
      run: dotnet pack ./src/*/*/Api.Contract.CustomerSet.Search.csproj --no-build -o ~/nuget  -c Release

    # Api.Contract.UserSet.Search.csproj

    - name: Restore Api.Contract.UserSet.Search.csproj
      run: dotnet restore ./src/*/*/Api.Contract.UserSet.Search.csproj

    - name: Build Api.Contract.UserSet.Search.csproj
      run: dotnet build ./src/*/*/Api.Contract.UserSet.Search.csproj --no-restore  -c Release

    - name: Pack Api.Contract.UserSet.Search.csproj
      run: dotnet pack ./src/*/*/Api.Contract.UserSet.Search.csproj --no-build -o ~/nuget  -c Release

    # Api.Contract.Incident.Create.csproj

    - name: Restore Api.Contract.Incident.Create.csproj
      run: dotnet restore ./src/*/*/Api.Contract.Incident.Create.csproj

    - name: Build Api.Contract.Incident.Create.csproj
      run: dotnet build ./src/*/*/Api.Contract.Incident.Create.csproj --no-restore  -c Release

    - name: Pack Api.Contract.Incident.Create.csproj
      run: dotnet pack ./src/*/*/Api.Contract.Incident.Create.csproj --no-build -o ~/nuget  -c Release

    # Api.Contract.csproj

    - name: Restore Api.Contract.csproj
      run: dotnet restore ./src/*/*/Api.Contract.csproj

    - name: Build Api.Contract.csproj
      run: dotnet build ./src/*/*/Api.Contract.csproj --no-restore  -c Release

    - name: Pack Api.Contract.csproj
      run: dotnet pack ./src/*/*/Api.Contract.csproj --no-build -o ~/nuget  -c Release

    # Api.csproj

    - name: Restore Api.csproj
      run: dotnet restore ./src/*/*/Api.csproj

    - name: Build Api.csproj
      run: dotnet build ./src/*/*/Api.csproj --no-restore  -c Release

    - name: Pack Api.csproj
      run: dotnet pack ./src/*/*/Api.csproj --no-build -o ~/nuget  -c Release

    # Api.Test.csproj

    - name: Restore Api.Test.csproj
      run: dotnet restore ./src/*/*/Api.Test.csproj

    - name: Test Api.Test.csproj
      run: dotnet test ./src/*/*/Api.Test.csproj --no-restore  -c Release

    # Push

    - name: Push Packages
      if: ${{ github.ref == 'refs/heads/main' }}
      run: >
        dotnet nuget push "../../../nuget/*.nupkg"
        -s ${{ secrets.GG_NUGET_SOURCE_URL }}
        -k ${{ secrets.GG_NUGET_SOURCE_USER_PASSWORD }}
        --skip-duplicate
